[GPIO]
# GPIO pins for the used buttons and leds using the GPIO numbering aka "BCM" or "Broadcom"
#
## Led pin defines 
# Output pin for the battery warning led
pin_led_bat = 20

## Speaker pin defines
# Output pin that shutdowns or not the speaker
pin_shutdown_speaker = 14

## Wake up pin defines
# Output pin for waking up the voice microcontroller
pin_wkup_speech = 10

## Input button pin defines 
# Input pin for the hand mode button
pin_but_hand = 6
# Input pin for the camera mode button
pin_but_camera = 12
# Input pin for the speech mode button
pin_but_speech = 16

## Interrupt pin defines from the different devices
# Interrupt input pin from the EMG microcontroller
# pin_int_emg = 17
# Interrupt input pin from the motor control microcontroller
pin_int_motor_cont = 25
# Interrupt input pin from the capacitive control microcontroller
pin_int_capacitive_cont = 17
# Interrupt input pin from the voice microcontroller
pin_int_speech = 11

# bounce time for the buttons in ms
t_bounce = 200

[STATUS_LED]
# delay between status led checks
t_delay = 1

[BATTERY]
# Constants for the battery measurement
# delay between battery checks in seconds
t_delay = 2 

# hysteresis for the battery check in volt
hysteresis = 0.2

# minimum voltage of the battery in volt
voltage_min = 6.8


[speaker_control]
routeHandSound = /home/pi/Music/handMode.mp3
routeVoiceSound = /home/pi/Music/voiceMode.mp3
routeCameraSound = /home/pi/Music/cameraMode.mp3


[rgb_control]
# Output pin for the NeoPixel DIN RGB leds
pin_led_rgb = 13 
num_leds_rgb = 17
brightness = 0.2


[emg_device]
i2c_adress = 0x33
i2c_offset = 0
nr_bytes_send_receive = 2

# Maximum attempts in requesting information from the emg microcontroller via I2C
max_attempts = 3

# Range detection quality
min_quality = 0
max_quality = 100

# Accepted commands
accepted_commands = 0, 1, 2, 3


# Configuration data of the microcontroller which is controlling the capacitive sensors
[cc_hand]
i2c_adress = 0x42
i2c_offset = 0
nr_bytes_receive = 12
nr_bytes_per_sensor = 2
nr_used_sensors = 6

# Height of each sensor that if exceeded, the associated finger stops. if the palm is exceeded, all fingers stop.
[cc_heights]
pinky_height = 1700
ring_height = 1700
middle_height = 1200
index_height = 1700
thumb_height = 1700
palm_height = 1700


# Configuration data of the speech microcontroller
[cmd_speech]
i2c_adress = 0x22
i2c_offset = 0
nr_bytes_receive = 2

# Maximum attempts in requesting information from the speech microcontroller via I2C
max_attempts = 3

# Accepted commands
# Said "uno"
uno = 0x11
# Said "dos"
dos = 0x19
# Said "tres"
tres = 0x1d
# Said "cuatro"
cuatro = 0x1f
# Said "cinco"
cinco = 0x1
# Unknown/Background noise
ruido = 0x0

# Range detection quality
min_quality = 0
max_quality = 100


# Configuration data for the object recognition
[object_rec]

# Accepted objects to recognize. Must be objects that are in the file coco.names
accepted_objects = person, cup, tv, chair, scissors, bottle, mouse, keyboard

# Range of acceptable detection quality
min_quality = 45
max_quality = 100


# Paths of the object detection model
labels_path = /home/pi/Desktop/Object_Detection_Files/coco.names
model_config_path = /home/pi/Desktop/Object_Detection_Files/ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt
model_weights_path = /home/pi/Desktop/Object_Detection_Files/frozen_inference_graph.pb
camera_index = 0
camera_width = 640
camera_height = 480


# Configuration data of the microcontroller which is controlling the mechanical hand
[mc_hand]
i2c_adress = 0x2b
i2c_offset = 0
cmd_read = 0
cmd_stop = 2
cmd_move = 3
cmd_individual_stop = 5000
nr_cmd_bytes = 1
nr_status_bytes = 1
nr_bytes_per_finger = 2
nr_bytes_send_recieve = 11

# fingers means number of motors or positions: little/ring(they have one motor), middle, index, thumb0, thumb1
nr_used_fingers = 5


[minMaxValues]
# min/max values when a finger is moved to #max position, TODO need to be tested with the hardware what values correspond to the correct position
# TODO this config data corresponds to a 12bit resolution of the position measurement ans suposes that a small value indicates a close position and a big value open position of the fingers
ring_max = 3700
ring_min = 200
middle_max = 3700
middle_min = 200
index_max = 3700
index_min = 200
thumb0_max = 3700
thumb0_min = 200
thumb1_max = 3700
thumb1_min = 200 


[positions]
# Predefined positions of the hand
# DATA FORMAT: pX_FINGER = VALUE
# X: represents the position number
# FINGER: represents the corresponding finger with an element of {ring, middle, index, thumb0, thumb1}
# thumb0 is linear and thumb1 rotative
#
# position 0: all open
# ring pos: open, middle pos: open, index pos: open, thumb1 (linear movement): open
# thumb1 (rotate movement) positioning ist not working right now set to 0
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p0_ring = 700
p0_middle = 3000
p0_index = 3000
p0_thumb0 = 3000
p0_thumb1 = 3000
# position 1: For pointing, typing on a keyboard or press a switch
# ring pos: close, middle pos: close, index pos: open, thumb1 (rotational movement): close ,thumb0 (linear movement): close
# thumb1 (rotate movement) positioning ist not working right now set to 0
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p1_ring = 3000
p1_middle = 700
p1_index = 3000
p1_thumb0 = 800
p1_thumb1 = 700
# position 2: For grabing a cylinder (bottle, glass, etc)
# ring pos: move, middle pos: move, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p2_ring = 3000
p2_middle = 700
p2_index = 700
p2_thumb0 = 800
p2_thumb1 = 700
# position 3: For grabing a sphere 
# ring pos: move, middle pos: move, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# This differs with position 2 in how much we move the rotate thumb
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
#p3_ring = 3000
#p3_middle = 700
#p3_index = 700
#p3_thumb0 = 800
#p3_thumb1 = 700
p3_ring = 700
p3_middle = 3000
p3_index = 700
p3_thumb0 = 3000
p3_thumb1 = 700
# position 4: For grabing a palmer
# ring pos: move, middle pos: move, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# This differs with position 2 and 3 in how much we move the rotate thumb
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
#p4_ring = 3000
#p4_middle = 700
#p4_index = 700
#p4_thumb0 = 800
#p4_thumb1 = 700
p4_ring = 3000
p4_middle = 700
p4_index = 3000
p4_thumb0 = 800
p4_thumb1 = 3000
# position 5: For tip movement
# ring pos: open, middle pos: open, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p5_ring = 700
p5_middle = 3000
p5_index = 700
p5_thumb0 = 800
p5_thumb1 = 700
# position 6: For lateral movement
# ring pos: move, middle pos: move, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# This differs with position 2, 3 and 4 in how much we move the rotate thumb
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p6_ring = 3000
p6_middle = 700
p6_index = 700
p6_thumb0 = 800
p6_thumb1 = 700
# position 7: For hook movement
# ring pos: move, middle pos: move, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# This differs with position 2, 3, 4 and 6 in how much we move the rotate thumb
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p7_ring = 3000
p7_middle = 700
p7_index = 700
p7_thumb0 = 800
p7_thumb1 = 700
# position 8: For tripod movement
# ring pos: open, middle pos: move, index pos: move, thumb0 (linear movement): move
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p8_ring = 700
p8_middle = 700
p8_index = 3000
p8_thumb0 = 800
p8_thumb1 = 700
# position 9: For peace movement
# ring pos: close, middle pos: open, index pos: open, thumb0 (linear movement): close
# thumb1 (rotate movement) positioning ist not working right now set to 0 
# ring positioning is reverse to other fingers, so open is 700 and close is 3000
p9_ring = 3000
p9_middle = 3000
p9_index = 3000
p9_thumb0 = 800
p9_thumb1 = 700